[package]
name = "fpv-computer-vision-api"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.0"
image = "0.25.1"
rocket = "0.5.0"
round = "0.1.2"

[[bin]]
name = "fpv-computer-vision-api"
path = "main.rs"
